# repo A: .github/workflows/reporting_action_poc.yml
name: Reporting POC
on:
  workflow_call:
    inputs:
      module:
        description: "Which module triggered"
        required: true
        type: string
    secrets:
      PAT:
        required: false
permissions:
  contents: read  # укажите минимум, что нужно внутри этого workflow
jobs:
  run-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Module is ${{ inputs.module }}"
