name: Run Remote Reporting

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Optional base ref (tag/commit)"
        required: false
      head:
        description: "Optional head ref (tag/commit)"
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  call-remote-a:
    uses: khandramai/a/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/a
      artifact_name: report-a
    secrets: inherit

  call-remote-b:
    needs: call-remote-a
    uses: khandramai/b/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/b
      artifact_name: report-b
    secrets: inherit

  collect-reports:
    needs: [call-remote-a, call-remote-b]
    runs-on: ubuntu-latest
    steps:
      - name: Download all report artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: report-*
          path: reports
          merge-multiple: false
          if-no-artifact-found: warn

      - name: List downloaded reports
        run: |
          if [ -d reports ]; then
            ls -R reports
          else
            echo "No reports directory (no artifacts downloaded)."
          fi

      - name: Re-upload aggregated reports (optional)
        if: ${{ hashFiles('reports/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: all-reports
          path: reports
