name: Run Remote Reporting

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Optional base ref (tag/commit)"
        required: false
      head:
        description: "Optional head ref (tag/commit)"
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  call-remote-a:
    uses: khandramai/a/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/a
    secrets: inherit

  call-remote-b:
    needs: call-remote-a
    uses: khandramai/b/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/b
    secrets: inherit
