name: Run Remote Reporting

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Optional base ref (tag/commit)"
        required: false
      head:
        description: "Optional head ref (tag/commit)"
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  call-remote-a:
    uses: khandramai/a/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/a
    secrets: inherit

  call-remote-b:
    needs: call-remote-a
    uses: khandramai/b/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/b
    secrets: inherit

    collect-reports:
      needs: [ call-remote-a, call-remote-b ]
      runs-on: ubuntu-latest
      steps:
        - name: Download all artifacts from this run
          uses: actions/download-artifact@v4
          with:
            path: reports

        - name: List downloaded reports
          run: ls -R reports

        - name: Re-upload aggregated reports (optional)
          uses: actions/upload-artifact@v4
          with:
            name: all-reports
            path: reports
