- name: Repository dispatch
  uses: actions/github-script@v7
  with:
    github-token: ${{ secrets.REPORTING_TRIGGER_PAT }}
    script: |
      await github.rest.repos.createDispatchEvent({
        owner: 'khandramai',
        repo: 'changes-reporting-poc',
        event_type: 'run-report',
        client_payload: { reason: 'nightly' }
      })
