name: Run Remote Reporting

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Optional base ref (tag/commit)"
        required: false
      head:
        description: "Optional head ref (tag/commit)"
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  call-remote-a:
    uses: khandramai/a/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/a
      artifact_name: report-a
    secrets: inherit

  call-remote-b:
    needs: call-remote-a
    uses: khandramai/b/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/b
      artifact_name: report-b
    secrets: inherit

  collect-reports:
    needs: [call-remote-a, call-remote-b]
    runs-on: ubuntu-latest
    steps:
      - name: Download all report artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: report-*
          path: reports
          merge-multiple: false
          if-no-artifact-found: warn

      - name: Combine HTML reports with shared styling
        shell: bash
        run: |
          set -Eeuo pipefail

          OUT=combined.html

          cat > "$OUT" <<'HTML'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <title>Combined Schema Changes Report</title>
            <style>
              body { margin: 2rem auto; max-width: 900px; font: 16px/1.6 -apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif; color:#24292f; background:#fff; }
              h1,h2,h3 { border-bottom:1px solid #d0d7de; padding-bottom:.3rem; }
              pre,code { font-family: ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace; }
              pre { background:#f6f8fa; padding:12px; border-radius:6px; overflow:auto; }
              table { border-collapse: collapse; width: 100%; }
              th,td { border:1px solid #d0d7de; padding:6px 10px; }
              blockquote { color:#57606a; border-left:4px solid #d0d7de; padding:0 1rem; margin:0; }
              hr { border: 0; border-top: 1px solid #d0d7de; margin: 2rem 0; }
              .repo-section { margin-bottom: 3rem; }
              .repo-badge { display:inline-block; font-size:.9rem; background:#f6f8fa; border:1px solid #d0d7de; border-radius:999px; padding:.2rem .6rem; margin-left:.5rem; }
            </style>
          </head>
          <body>
            <h1>Combined Schema Changes Report</h1>
          HTML

          shopt -s nullglob
          for f in reports/**/report.html; do
            repo_folder="$(basename "$(dirname "$f")")"
            echo "<div class=\"repo-section\">" >> "$OUT"
            echo "<h2>Repository <span class=\"repo-badge\">${repo_folder}</span></h2>" >> "$OUT"
            # Вставляем только содержимое <body> из каждого отчёта
            sed -n '/<body[^>]*>/,/<\/body>/p' "$f" | sed '1d;$d' >> "$OUT"
            echo "</div><hr/>" >> "$OUT"
          done

          echo "</body></html>" >> "$OUT"

      - name: Upload combined report
        uses: actions/upload-artifact@v4
        with:
          name: combined-report
          path: combined.html
