name: Run Remote Reporting

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Optional base ref (tag/commit)"
        required: false
      head:
        description: "Optional head ref (tag/commit)"
        required: false

permissions:
  contents: read
  pull-requests: write

jobs:
  call-remote-a:
    uses: khandramai/a/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/a
      artifact_name: report-a
    secrets: inherit

  call-remote-b:
    needs: call-remote-a
    uses: khandramai/b/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
      repository: khandramai/b
      artifact_name: report-b
    secrets: inherit

  collect-reports:
    needs: [call-remote-a, call-remote-b]
    runs-on: ubuntu-latest
    steps:
      - name: Download all report artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: report-*
          path: reports
          merge-multiple: false
          if-no-artifact-found: warn

      - name: Combine HTML reports
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Combined Schema Changes Report</title></head><body>' > combined.html

          for f in reports/**/report.html; do
            echo "<h1>Report: $(basename $(dirname $f))</h1>" >> combined.html
            # вырезаем body содержимое из каждого файла
            sed -n '/<body[^>]*>/,/<\/body>/p' "$f" | sed '1d;$d' >> combined.html
            echo "<hr/>" >> combined.html
          done

          echo '</body></html>' >> combined.html

      - name: Upload combined report
        uses: actions/upload-artifact@v4
        with:
          name: combined-report
          path: combined.html
