name: Run Remote Reporting

on:
  workflow_dispatch:
    inputs:
      base:
        description: "Optional base ref (tag/commit)"
        required: false
      head:
        description: "Optional head ref (tag/commit)"
        required: false

permissions:
  contents: read
  pull-requests: write

#jobs:
#  call-remote:
#    uses: khandramai/a/.github/workflows/reporting_action.yml@main
#    with:
#      base: ${{ inputs.base }}
#      head: ${{ inputs.head }}



jobs:
  call-remote:
    strategy:
      matrix:
        repo: [khandramai/a, khandramai/b]
    uses: ${{ matrix.repo }}/.github/workflows/reporting_action.yml@main
    with:
      base: ${{ inputs.base }}
      head: ${{ inputs.head }}
    secrets: inherit