name: Trigger remote Reporting

on:
  workflow_dispatch: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger reporting_action_poc.yml in changes-reporting-poc
        uses: actions/github-script@v7
        with:
          token: ${{ secrets.REPORTING_TRIGGER_PAT }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'khandramai',
              repo: 'changes-reporting-poc',
              workflow_id: 'reporting_action_poc.yml',
              ref: 'main'
            })
